name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        id: cache-info
        run: |
          perl -V > perlversion.txt
          ls -l perlversion.txt
          perl ./maint/helper.pl gha-get-cache-output

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ${{ fromJSON( steps.cache-info.outputs.paths ) }}
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}-${{ hashFiles('cpanfile') }}-${{ secrets.CACHE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}-${{ hashFiles('cpanfile') }}-${{ secrets.CACHE_VERSION }}

      - name: CPAN client
        run: perl ./maint/helper.pl setup-cpan-client
      - name: Install packages
        run: perl ./maint/helper.pl install-native-packages
      - name: Install Static Dependencies
        run: perl ./maint/helper.pl install-via-cpanfile
      - name: Run tests
        run: perl ./maint/helper.pl run-tests
      - name: Create tarball
        id: create-tarball
        run: perl ./maint/helper.pl create-dist-tarball
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-dist
          path: ${{  steps.create-tarball.outputs.dist-tarball-file }}
