name: msys2-mingw

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: windows-latest

    strategy:
      fail-fast: false

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        shell: powershell

      - uses: actions/checkout@v2

      - name: Set up Perl
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-perl

      - name: perl -V
        run: |
          perl -V

      - name: Prepare for cache
        id: cache-info
        run: |
          perl -V > perlversion.txt
          ls perlversion.txt
          perl ./maint/helper.pl gha-get-cache-output

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ${{ fromJSON( steps.cache-info.outputs.paths ) }}
          key: ${{ runner.os }}-build-msys2-${{ hashFiles('perlversion.txt') }}-${{ hashFiles('cpanfile') }}
          restore-keys: |
            ${{ runner.os }}-build-msys2-${{ hashFiles('perlversion.txt') }}-${{ hashFiles('cpanfile') }}

      - name: CPAN client
        run: perl ./maint/helper.pl setup-cpan-client
      - name: Install packages
        run: perl ./maint/helper.pl install-native-packages
      - name: Install Static Dependencies
        run: perl ./maint/helper.pl install-via-cpanfile
      - name: Create tarball
        id: create-tarball
        run: perl ./maint/helper.pl create-dist-tarball
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: win32-dist
          path: ${{  steps.create-tarball.outputs.dist-tarball-file }}

      - name: Build .msi
        id: build-msi
        run: perl ./maint/helper.pl build-msi
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: win32-msi
          path: ${{  steps.build-msi.outputs.asset }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{  steps.build-msi.outputs.asset }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
